name: Release

on:
  push:
    tags:
      - "*"

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install fyne-cross
        run: go get github.com/fyne-io/fyne-cross
      - name: Build
        run: |
          fyne-cross linux -name go-sheet-linux-amd64 -arch amd64
          fyne-cross windows -arch amd64
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            fyne-cross/bin/linux-amd64/go-sheet-linux-amd64
            fyne-cross/bin/windows-amd64/go-sheet.exe
